### PR TITLE
Allow root database usernames besides 'root' and 'postgres'

### PR DESCRIPTION
**Pull request by NickLaMuro**
Description
-----------

While this isn't helpful when creating your own database, if you were to make use of something like RDS or other databases as a service, you usually have the ability to create a root account with the username that isn't `root` or `postgres`.

With things the way they are, you would be required to always maintain the above connections to make use of the `bamboo::database` recipe. This change keeps the original functionality in place, but makes it possible the change the default through attributes via the following:

    default[:bamboo][:database][:external]       = true
    default[:bamboo][:database][:root_user_name] = 'my_root_username'

**Test Suite issues**

I also fixed some issues with the integration test suite:

* Fixed package name descrepecy issues between ubuntu and centos
* Fixed a mysql package issue on ubuntu 12 where mysql 5.6 wasn't available
* Fixed and issue in the tests where mysql on centos wasn't running as a service, so I didn't test that on that family (the port is still active, and we are testing for that, so I think that is good enough)

There is still one outstanding issue where on ubuntu 14.04, the apt recipe doesn't get run even though it is in the dna.json as the first recipe.  After a failed converge, doing a `kitchen login` and running `sudo apt-get update`, I could re-run the converge and it worked fine.  Not sure why this happens, but it was a minor issue that I wasn't going to investigate much further.

If you prefer not to have any of these changes, I can revert the test changes commit before we merge, but I wanted something for myself to validate that none of the changes I was making was breaking the existing recipe.

### CODE REVIEW

**Comment by ramonskie** [comment]
nice thanks for your contribution :+1:

**Comment by ramonskie** [comment]
i fixed the apt issue in
https://github.com/ramonskie/bamboo/commit/93470a736d82437e9fd2346817d8e113db7c8170

but its a bit hacky and should be addressed

**Comment by NickLaMuro** [comment]
Thanks for the merge and the great cookbook!

P.S. I have seen worse hacks :smile:

**Comment by ramonskie** [comment]
i have identified the problem is in the database:postgresql cookbook
that install chef_gem 'pg' that needs build essentials at compile_time

and because build essentials compile time go's before apt at compile time the apt-get update is not executed. i see allot of users who are depending on that cookbook have this kind of issues with this in combination with test-kitchen

so for now we keep this change :)

**Comment by NickLaMuro** [comment]
@ramonskie Didn't notice this before, but it looks like you have a typo in the default attributes:

https://github.com/ramonskie/bamboo/blob/9b1b8f4c9db84ce69822e69981324852e153de49/attributes/default.rb#L109

Which should be doing the same thing as https://github.com/ramonskie/bamboo/commit/72d63f4d97da43a39077e89022288b8b729139a6 (assuming it was spelled correctly).

**Comment by ramonskie** [comment]
thanks :) will fix that

**Pull request merged**
