### PR TITLE
Allow custom data_dir for MySQL

### PR DESCRIPTION
**Pull request by wolf31o2**
I was using the previous versions of the cookbook, which used the older `mysql::server` recipe. I had a custom `mysql[:data_dir]` set. This should allow for seamless upgrades from `<= 1.3.0` to `> 1.3.0` without breaking the database.

### CODE REVIEW

**Comment by wolf31o2** [comment]
The test failures are fixed in #14

**Comment by ramonskie** [comment]
yes i also had the same issue
at the end i did just a mysqldump and import

**Comment by wolf31o2** [comment]
This was with the old cookbook < 1.3.0 that used the 3.0 version of mysql cookbook. Going from 1.2.9 to 1.3.0 is where I hit this.

**Comment by ramonskie** [comment]
need to release it though do you need it soon?

**Comment by wolf31o2** [comment]
Next release is fine. I am hand-editing cookbook at the moment. Having
issues w/ mysql on second run. Will investigate and report. (Fails doing
grant on already granted bamboo user in mysql)

**Pull request merged**
