### PR TITLE
Relax constraints

### PR DESCRIPTION
**Pull request by patcon**
Pin backup gem version. Relax patch level cookbook versions.

See: https://github.com/ramonskie/bamboo/commit/cf644bc7ede4d8c88884ba2cde0ae15c60113546#commitcomment-12117788

### CODE REVIEW

**Comment by ramonskie** [comment]
this 
```
backup_install node.name do
  version '4.1.10'
end
```
already pinned in the cookbook

why set this in my cookbook and not pin on backup version
i don't know if you used the backup cookbook before
and use s3 function not from amazone?

because amazone andthe s3 api's did change drastically in the last few months

**Comment by patcon** [comment]
Buuut... I thought you were saying that you couldn't unpin the backup cookbook version in metadata.rb because you needed a specific fog version. And I was saying that pinning a cookbook to a specific version in a community cookbook (designed to be used by others?) is a bad practice, that happens to break my chef repo (when resolving with berkshelf) so I was trying to allow us to *unpin* the backup cookbook version by *pinning* the backup gem to a specific working version. Does that make sense? Am i misunderstanding what you need to see in order to let us remove this constraint from metadata.rb:

    depends 'backup',             '= 0.2.4'

Please help me understand :)

**Comment by ramonskie** [comment]
the backup gem and the fog gem are tightly integrated
the s3 api had some major changes from 1.24 till 1.28
but this is only if you use the s3 protocol outside amazone (like ceph for example)

so thats why i pin this because i also contribute some small things to the backup cookbook from damm one in a while.

so when there is a new version and i notice some awsome feature or bug fix that we really need to upgrade it i will do so.

**Comment by patcon** [comment]
ok thanks. So what can I do to allow you to feel comfortable unpinning the backup cookbook?

**Comment by ramonskie** [comment]
well not much.
but why are you so keen on not pinning cookbook versions
because its a common practice in chef cookbooks

**Comment by patcon** [comment]
Not trying to be challenging, but pinning specific versions down to the patch version is totally an anti-pattern as far as I've seen. In fact, I've never seen anyone use the "=" sign in a community cookbook, at least one that's widely used. Honestly, I'd be surprised if you could point me to one :)

Like if one or two other cookbook maintainers that I use in my repo decided to treat version constraints this way, it would break everything quickly. It's not sustainable

If I got a second opinion from the #chef IRC channel, and could link you that, might it sway your stance?

**Comment by ramonskie** [comment]
Ofcours

**Comment by patcon** [comment]
thanks. fyi this is my dependency graph with just *two* community atlassian cookbooks. Hopefully you can see why it feels bad in a situation like this for community cookbooks to pin versions any more strictly than absolutely necessary to work

graph

(working on that second opinion, but no one online right now)

**Comment by ramonskie** [comment]
So you deploy multiple Atlassian products on one machine?  Otherwise I don't see why you should have any dependency issues

**Comment by mrjcleaver** [comment]
Max of any one type of Atlassian application (i.e. max one Bamboo), but yes, possibly Stash + Bamboo on the same box.

**Comment by patcon** [comment]
do you use berkshelf? If you maintain your chef-repo with berkshelf (and manage multiple servers and server types from that), then you will run into the situation where overly-opinionated cookbook like this one break the dependency graph resolution and no possible graph is available

**Comment by patcon** [comment]
Anyhow, if we can't resolve this, I can just fork and push a more friendly cookbook to the community site under a different namespace. You're welcome to extract the serverspec tests I add later.

**Comment by shrinathaithal** [comment]
Totally agree with the sentiments reflected here, I have never seen an "=" pinning used so far. Also, I am not able to find the pinned version on supermarket, dependency is broken.

**Comment by ramonskie** [comment]
the dependency is not broken please check the berksfile.
if you read a few issues in his repo you will that someone hijacked his backup cookbook a few years ago and stopped maintaining it.

so if you use berks install/update and berks upload you should have no issues with uploading your cookbook to your chef server.

also its not a good idea to put two atlassian prodcuts on the same server
especially bamboo and stash as they are the most cpu/mem intrusive

**Comment by patcon** [comment]
> also its not a good idea to put two atlassian prodcuts on the same server
> especially bamboo and stash as they are the most cpu/mem intrusive 

Sorry if I'm beating a dead horse @ramonskie (I really appreciate you despite our small disagreement!), but if cookbook users are managing their organizational chef-repo from a berksfile and using chef's local_mode (to avoid overhead of chef-server), then we run into the constraint clash even when responsibly hosting atlassian tools on separate servers

**Comment by ramonskie** [comment]
i can accept most of them except for the backup

**Comment by mrjcleaver** [comment]
> also its not a good idea to put two atlassian prodcuts on the same server
> especially bamboo and stash as they are the most cpu/mem intrusive

I agree if you run them at scale. Do you assert this for team of 10?

**Comment by ramonskie** [comment]
since the latest release this pull request can be closed agree?

**Pull request closed without merging**
