### PR TITLE
removing version constraint for postgresql, version specified did not…

### PR DESCRIPTION
**Pull request by jeremyfryer**
… work with Centos 7.1

### CODE REVIEW

**Comment by jeremyfryer** [comment]
I would like to remove the version constraint on postgresql cookbook. The 3.4.16 was not working on Centos 7.1 for me. Also others can specify a specific version in there wrapper cookbook if necessary.

**Comment by aaronblythe** [comment]
For reference #38 and https://github.com/hw-cookbooks/postgresql/issues/302

**Comment by ramonskie** [comment]
which on is working for you?
because we had allot issues with the postgresql cookbook. the last couple of months
so i really want to pin a working version

**Comment by jeremyfryer** [comment]
I was able to use 'postgresql', '~> 4.0.6'

**Comment by ramonskie** [comment]
done in commit https://github.com/ramonskie/bamboo/commit/6b6ce5661298ba253c2b923ecf394129ad676e58

**Pull request closed without merging**
