### PR TITLE
Less opinionated dependencies

### PR DESCRIPTION
**Pull request by patcon**
This cookbook depends on lots of others (which is a-ok), but you use pessimistic version constraints generously, seemingly when there has not actually been a breakage in the upstream cookbook. Due to this, Berkshelf is unable to resolve the constraints with your cookbook.

If I submit a PR and relax some things, would you consider accepting?

Thanks!

### CODE REVIEW

**Comment by patcon** [comment]
OK, this would strike me as the minimum we'd want to do, as it previously pinned the minor version, which only indicates new features (the major version is breaking changes, which someone arguable might want to pin)

In general, it's not usually great to pin versions in cookbooks unless you've learned there's an incompatibility. And even then, you probably want just "greater than" rather than pesseimistic greater than. The pessemism seems like something best left to people to accomodate in their own infrastructure, rather  than forcing constraints that might not apply, and breaking the cookbook for others :)

If you're willing to relax more, just let me know and I'll create another PR after this one. (For now, this goes a long way to fixing!)

**Comment by patcon** [comment]
OK, I sense this is perhaps too relaxed, but the opinionatedness of your cookbook was preventing it from playing nicely with berkshelf resolution :)

Could we discuss what breaks in the past required pinning, and only add constraints that solve established problems? Otherwise, we're doing work that the dependency resolution tool should be doing (ie. "protecting" users, but being over-bearing about it)

Thanks for hearing me out!

**Comment by mvdkleijn** [comment]
By this "... to accomodate in their own infrastructure ..." I gather you mean apply version constraints only in wrapper cookbooks unless this cookbook is dependent on / broken by a specific version of a dependency?

**Comment by patcon** [comment]
Yep :) i was overly wordy.

**Comment by ramonskie** [comment]
well i a few cookbooks where we are depending on does not follow there versioning very well.
the installation broke on apache, mysql, database, 
i think the apache2 cookbook should definitely be set to a pessimistic constraint
because if a new major apache version arrives it will probably break
same with the mysql cookbook

**Comment by patcon** [comment]
Fair enough, I'll push that change next time I work on this. Thanks!

**Comment by patcon** [comment]
And by the way, my stance (which we're free to disagree on) is that locking in something best done at the user infra level, and the main exception is for situations like "this is definitely broken and we've seen it", not "semver says this *could* theoretically break next version" (because not all major bumps break things for all depending cookbooks). The conservatism in the latter is something that seems best-suited to someone's individual infra (ie Berksfile.lock on chef-server environments)

If you pre-emptively lock, then when I add your cookbook and resolve, I actually get the old version through Berksfile dep resolution, and use that blindly. This is instead of getting the new, and then filing a bug and perhaps even submitting a simple fix :)

**Pull request closed without merging**
